# Generated by Django 4.2.10 on 2024-02-29 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_about_alter_post_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
